language: node_js
node_js:
  - 11
# before_script:
script: yarn && npm run build && npm run test
git:
  quiet: true
  depth: false
  submodules: true
branches:
  only:
  - master
  # :NOTE: pull request builds are on, so this takes care of feature branches
  - /^(release|hotfix)\/.*/
cache:
  yarn: false
  npm: false
#   directories:
#   - "/tmp/holochain/target"
#   cargo: true
